apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: snapshot-webhook
webhooks:
- name: snapshot-webhook.codesink.net
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - persistentvolumeclaims
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: snapshot-webhook
      name: snapshot-webhook
    # Set to not-null. Will be fixed by the snapshot-webhook when it initalizes.
    caBundle: bm90bnVsbA==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-webhook
  namespace: snapshot-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshot-webhook
  namespace: snapshot-webhook
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-webhook
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get", "list", "create", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-webhook
  namespace: snapshot-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snapshot-webhook
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: snapshot-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snapshot-webhook
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: snapshot-webhook
  namespace: snapshot-webhook
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: snapshot-webhook
  namespace: snapshot-webhook
  labels:
    app: snapshot-webhook
spec:
  selector:
    matchLabels:
      app: snapshot-webhook
  template:
    metadata:
      labels:
        app: snapshot-webhook
    spec:
      serviceAccountName: snapshot-webhook
      containers:
      - image: justinbarrick/snapshot-admission-controller
        imagePullPolicy: Always
        name: snapshot-webhook
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: snapshot-webhook
  namespace: snapshot-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: snapshot-webhook
